create table categoria (codigo int8 generated by default as identity, descricao varchar(255), nome varchar(255), primary key (codigo));
create table investimento (codigo int8 generated by default as identity, codigo_ativo varchar(255), data_compra date, quantidade_cotas int4, valor_cota float8, fk_codigo_categoria int8, primary key (codigo));
alter table if exists investimento add constraint FKf0crt608cqkxw098stsb314h3 foreign key (fk_codigo_categoria) references categoria;
